spring.datasource.url=jdbc:mysql://localhost:3306/category_db
spring.datasource.username=root
spring.datasource.password=76231677

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
cloudinary.cloud_name=dawofbslx
cloudinary.api_key=574786311896298
cloudinary.api_secret=RpFlEejOA9yBjehEul3XUFdPji0

server.port=${PORT:8080}
